videojs/mpd-parser

src/toM3u8.js, test/manifests/maat_vtt_segmentTemplate.js, test/toM3u8.test.js
Right now selection a caption will produce an error, let's turn off this feature until the bugs are worked out.
=> fix: switch off in-manifest caption support

.travis.yml, src/inheritAttributes.js, src/segmentTemplate.js, src/toPlaylists.js, test/index.test.js, test/inheritAttributes.test.js, test/manifests/maat_vtt_segmentTemplate.js, test/segmentTemplate.test.js, test/toPlaylists.test.js
This adds support for the following SegmentTemplate features
* template string identifier replacement with padding format tag support
* $$
* $RepresentationID$
* $Number%0{x}d$
* $Bandwidth%0{x}d$
* $Time%0{x}d$
* build segments from **SegmentTimeline** element
=> add support for SegmentTemplate padding format string and SegmentTimeline

scripts/rollup.config.js
The purpose of this change is to babel the ES6 module export for compatibility. The project may be using features that are not common or considered experimental.
=> fix: babel es module

src/segment/urlType.js, test/segment/segmentBase.test.js, test/segment/segmentList.test.js, test/segment/segmentTemplate.test.js, test/segment/urlType.test.js
All byteRanges in DASH are inclusive as per https://tools.ietf.org/html/rfc2616#section-14.35.1.
=> fix: make byteRange.length inclusive

package-lock.json, package.json, src/index.js, src/segment/segmentBase.js, src/segment/urlType.js, src/toM3u8.js, src/toPlaylists.js, test/manifests/maat_vtt_segmentTemplate.js, test/segment/segmentBase.test.js, test/segment/urlType.test.js, test/toM3u8.test.js, test/toPlaylists.test.js
Attempted fix for https://github.com/videojs/http-streaming/issues/162.
This appears to be working on the issue source.
- expose `sidxMapping` option on the `parse` method to allow modifying a complete master playlist with metadata from a parsed sidx box
- attach a `sidx` property with byteRange references to manifest objects generated with SegmentBase. This applies to both video and audio playlists
- replace media playlist segments with those generated from `sidx.references` when the `sidxMapping` option is given
```
{ 
src: "https://dash.akamaized.net/dash264/TestCases/10a/1/iis_forest_short_poem_multi_lang_480p_single_adapt_aaclc_sidx.mpd",
type: "application/dash+xml"
}
```
=> feat: add sidx information to segment base playlists

src/toM3u8.js
This can be when we have an mpd with captions without SIDX and video segments that use SIDX, like in ihttps://dash.edgesuite.net/akamai/test/caption_test/ElephantsDream/elephants_dream_480p_heaac5_1.mpd.
Fixes videojs/video.js#5289
=> fix: skip playlists without sidx

package-lock.json, package.json, scripts/rollup.config.js, src/index.js, src/stringToMpdXml.js, test/parseAttributes.test.js, test/utils.test.js
Brought up due to https://github.com/videojs/hls-fetcher/pull/35
~~Depends on: https://github.com/videojs/vhs-utils/pull/1~~ Out as 1.1.0, and now in this pull request.
=> feat: node support

src/index.js, src/inheritAttributes.js, src/toM3u8.js, test/index.test.js, test/inheritAttributes.test.js, test/manifests/location.js, test/manifests/location.mpd, test/manifests/locations.js, test/manifests/locations.mpd, test/toM3u8.test.js
=> feat: parse out Location element and return the first one

src/toM3u8.js, test/manifests/location.js, test/manifests/locations.js, test/manifests/maat_vtt_segmentTemplate.js, test/manifests/multiperiod-dynamic.js, test/manifests/multiperiod.js, test/manifests/segmentBase.js, test/manifests/segmentList.js, test/toM3u8.test.js
We cannot currently differentiate between cases when the `minimumUpdatePeriod` does not exist vs. when it is 0, since we set 0 as the default value in the first case. Since it is valid for the `minimumUpdatePeriod` to be either 0 or absent, we need to remove this default value.
=> feat: remove default value of 0 for minimumUpdatePeriod

index.html, src/toM3u8.js, test/index.test.js, test/manifests/vtt_codecs.js, test/manifests/vtt_codecs.mpd
We have a test video that uses non-vtt captions that is making it all the way through to the vtt segment loader. We cannot filter it as we don't expose CODECS on subtitle playlists. Now we expose that so we can filter downstream. We might also want to expose mimeType?
=> feat: subtitle codecs

src/index.js
We need to expose this so that we don't have to always re-parse master xml for sidx. We can just add sidx segments to playlist directly.
=> feat: expose add addSidxSegmentsToPlaylist

src/toM3u8.js, test/index.test.js, test/manifests/webmsegments.js, test/manifests/webmsegments.mpd
This PR adds support for parsing manifests with webm segments.
=> support for parsing manifests with webm segments.

test/manifests/webmsegments.js
The default for `minimumUpdatePeriod` was removed in #103
=> test: fix tests introduced in #79 that was not rebased on #103

src/stringToMpdXml.js, src/utils/object.js
Apparently we never set up browserstack for this project so we only ever tested on chrome/firefox/nodejs. With the switch to github ci in #111 ie 11 started to fail.
=> fix: fix edge case error handling on ie 11

package-lock.json, package.json, scripts/rollup.config.js
Also updates generator dependencies that would have caught this before it happened. See https://github.com/videojs/m3u8-parser/issues/119
=> fix: cjs dist should only import cjs

src/index.js, src/segment/segmentBase.js, src/toM3u8.js, test/index.test.js, test/manifests/audio-only.js, test/manifests/audio-only.mpd, test/manifests/maat_vtt_segmentTemplate.js, test/manifests/multiperiod-dynamic.js, test/manifests/multiperiod.js, test/manifests/vtt_codecs.js, test/segment/segmentBase.test.js, test/toM3u8.test.js
Currently we drop multiple playlists for the same group, when we should allow multiple renditions for the same group. This allows that to happen.
Fixes: #93 
Fixes: #105 
Fixes: #77
=> fix: export generateSidxKey, multiple audio/vtt playlists

src/inheritAttributes.js, src/toM3u8.js, test/index.test.js, test/inheritAttributes.test.js, test/manifests/608-captions.mpd, test/manifests/708-captions.js, test/manifests/708-captions.mpd
This is 708 caption signaling.
One limitation I found as part of this is that if multiple services are of the same language, they can't be represented in mediaGroups as they're defined right now. For example, the following 708 signal `1=lang:eng;2=lang:eng,war:1,er:1` will only surface the SERVICE2 item since both get added under media groups under `eng`.
=> 708 caption signaling

src/inheritAttributes.js, src/toPlaylists.js, test/inheritAttributes.test.js
This change helps avoid confusion between VHS-JSON timeline property and the DASH
SegmentTimeline attribute.
=> refactor: rename SegmentInfo property from timeline to segmentTimeline

src/parseAttributes.js, src/toM3u8.js, src/utils/string.js, test/manifests/608-captions.js, test/manifests/708-captions.js, test/manifests/location.js, test/manifests/locations.js, test/manifests/maat_vtt_segmentTemplate.js, test/manifests/multiperiod-dynamic.js, test/manifests/multiperiod-segment-list.js, test/manifests/multiperiod-segment-template.js, test/manifests/multiperiod-startnumber-removed-periods.js, test/manifests/multiperiod-startnumber.js, test/manifests/multiperiod.js, test/manifests/segmentBase.js, test/manifests/segmentList.js, test/manifests/vtt_codecs.js, test/manifests/webmsegments.js, test/toM3u8.test.js
It adds support for the 'FRAME-RATE' attribute. To make an mpd parser consistent with the m3u8 parser.
=> feat: add support for a frame-rate attribute

package-lock.json, package.json, src/playlist-merge.js, src/toM3u8.js, src/utils/list.js, test/utils.test.js
=> chore: remove ie 11 support

src/toM3u8.js, test/toM3u8.test.js
Fix the issue when the subtitles' `label` property was set from lang instead of label
=> fix(toM3u8): set label for vttPlaylist from label instead of lang

src/index.js, src/inheritAttributes.js, src/parseAttributes.js, src/toM3u8.js, test/inheritAttributes.test.js, test/toM3u8.test.js
Feature Added
--
**EventStream tag support**
Timed metadata can be embedded  in the DASH manifest with `<EventStream>` tags at the `<Period>` level. Each EventStream contains `<Event>` tags that represent each node of timed metadata. This pull request adds support for parsing EventStream and child Event tags and properties and returns a flattened collection of Event-like objects with the following properties:
```
{
end: number,
id: string,
messageData: string,
schemeIdUri: string,
start: number,
value: string,
contentEncoding: string,
presentationTimeOffset: number
}
```
This implementation is based off of https://dashif-documents.azurewebsites.net/Events/master/event.html#mpd-event-timing which is from the DASH spec ISO_IEC_23009 section 5.10.2.1.
=> feat: add EventStream support

src/inheritAttributes.js, test/inheritAttributes.test.js
fixes Event node parsing to account for `<Event>` node content first, then messageData. See: https://dashif-documents.azurewebsites.net/Events/master/event.html#mpd-event-timing
@messageData | O | specifies the value for the event stream element. The value space and semantics must be defined by the owners of the scheme identified in the @schemeIdUri attribute. _NOTE: the use of the message data is discouraged by content authors, it is only maintained for the purpose of backward-compatibility. Including the message in the Event element is recommended in preference to using this attribute. This attribute is expected to be deprecated in the future editions of this document._
-- | -- | --
=> fix: get event tag content

.github/workflows/ci.yml, .github/workflows/github-release.yml
* Update deprecated set-output command. This will stop working in June 2023. See [this post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
* Update actions to use Node 16 rather than Node 12. Github are currently migrating away from Node 12. See [this post](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
GabrielBB/xvfb-action is no longer maintained and there is no Node 16 version. Therefore it was replaced with coactions/setup-xvfb.
=> chore: Update CI and release workflows

src/inheritAttributes.js, test/inheritAttributes.test.js
Fix for a bug introduced in v1.2.0. This ensures that we correctly use the `manifestUri` when necessary in resolvedUris in segments from the mpd parser.
=> fix: use manifest uri in base urls

src/toM3u8.js, test/toM3u8.test.js
In DASH, the language property we set on VTT tracks should be accurate. As of now, this value is the label when it exists, THEN the language.
This change sets the language to the `lang` property if it exists, then the label, and then `en` by default.
=> fix: ensure vtt tracks language is set correctly
